version: "3.5"

services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:80
    networks:
      - myNetwork
    volumes:
      - ./php:/var/www/html/
    restart: always

  db:
    image: mysql:8.0
    networks:
      - myNetwork
    volumes:
      - ./mysql/data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: user_manager
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: mypwd
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 6603:3306
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
       - myNetwork
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
       - "8181:80"
    depends_on: 
        - db

networks:
  myNetwork: